// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: squad/marketmaker/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d370b66f25c44c1, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d370b66f25c44c1, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryMarketMakersRequest is the request type for the Query/MarketMakers RPC method.
type QueryMarketMakersRequest struct {
	Address    string             `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PairId     uint64             `protobuf:"varint,2,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty"`
	Eligible   string             `protobuf:"bytes,3,opt,name=eligible,proto3" json:"eligible,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMarketMakersRequest) Reset()         { *m = QueryMarketMakersRequest{} }
func (m *QueryMarketMakersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMarketMakersRequest) ProtoMessage()    {}
func (*QueryMarketMakersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d370b66f25c44c1, []int{2}
}
func (m *QueryMarketMakersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMarketMakersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMarketMakersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMarketMakersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMarketMakersRequest.Merge(m, src)
}
func (m *QueryMarketMakersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMarketMakersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMarketMakersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMarketMakersRequest proto.InternalMessageInfo

func (m *QueryMarketMakersRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryMarketMakersRequest) GetPairId() uint64 {
	if m != nil {
		return m.PairId
	}
	return 0
}

func (m *QueryMarketMakersRequest) GetEligible() string {
	if m != nil {
		return m.Eligible
	}
	return ""
}

func (m *QueryMarketMakersRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryMarketMakersResponse is the response type for the Query/MarketMakers RPC method.
type QueryMarketMakersResponse struct {
	Marketmakers []MarketMaker `protobuf:"bytes,1,rep,name=marketmakers,proto3" json:"marketmakers"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMarketMakersResponse) Reset()         { *m = QueryMarketMakersResponse{} }
func (m *QueryMarketMakersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMarketMakersResponse) ProtoMessage()    {}
func (*QueryMarketMakersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d370b66f25c44c1, []int{3}
}
func (m *QueryMarketMakersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMarketMakersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMarketMakersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMarketMakersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMarketMakersResponse.Merge(m, src)
}
func (m *QueryMarketMakersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMarketMakersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMarketMakersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMarketMakersResponse proto.InternalMessageInfo

func (m *QueryMarketMakersResponse) GetMarketmakers() []MarketMaker {
	if m != nil {
		return m.Marketmakers
	}
	return nil
}

func (m *QueryMarketMakersResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryIncentiveRequest is the request type for the Query/Incentive RPC method.
type QueryIncentiveRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryIncentiveRequest) Reset()         { *m = QueryIncentiveRequest{} }
func (m *QueryIncentiveRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIncentiveRequest) ProtoMessage()    {}
func (*QueryIncentiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d370b66f25c44c1, []int{4}
}
func (m *QueryIncentiveRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIncentiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIncentiveRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIncentiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIncentiveRequest.Merge(m, src)
}
func (m *QueryIncentiveRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIncentiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIncentiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIncentiveRequest proto.InternalMessageInfo

func (m *QueryIncentiveRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryIncentiveResponse is the response type for the Query/Incentive RPC method.
type QueryIncentiveResponse struct {
	Incentive Incentive `protobuf:"bytes,1,opt,name=incentive,proto3" json:"incentive"`
}

func (m *QueryIncentiveResponse) Reset()         { *m = QueryIncentiveResponse{} }
func (m *QueryIncentiveResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIncentiveResponse) ProtoMessage()    {}
func (*QueryIncentiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d370b66f25c44c1, []int{5}
}
func (m *QueryIncentiveResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIncentiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIncentiveResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIncentiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIncentiveResponse.Merge(m, src)
}
func (m *QueryIncentiveResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIncentiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIncentiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIncentiveResponse proto.InternalMessageInfo

func (m *QueryIncentiveResponse) GetIncentive() Incentive {
	if m != nil {
		return m.Incentive
	}
	return Incentive{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "squad.marketmaker.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "squad.marketmaker.v1beta1.QueryParamsResponse")
	proto.RegisterType((*QueryMarketMakersRequest)(nil), "squad.marketmaker.v1beta1.QueryMarketMakersRequest")
	proto.RegisterType((*QueryMarketMakersResponse)(nil), "squad.marketmaker.v1beta1.QueryMarketMakersResponse")
	proto.RegisterType((*QueryIncentiveRequest)(nil), "squad.marketmaker.v1beta1.QueryIncentiveRequest")
	proto.RegisterType((*QueryIncentiveResponse)(nil), "squad.marketmaker.v1beta1.QueryIncentiveResponse")
}

func init() {
	proto.RegisterFile("squad/marketmaker/v1beta1/query.proto", fileDescriptor_6d370b66f25c44c1)
}

var fileDescriptor_6d370b66f25c44c1 = []byte{
	// 994 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x96, 0x4f, 0x6f, 0xdc, 0xc4,
	0x1b, 0xc7, 0xe3, 0xec, 0x36, 0xfd, 0x65, 0xda, 0x9f, 0x84, 0x86, 0x16, 0x36, 0x16, 0xda, 0x4e,
	0xcd, 0x9f, 0x14, 0x68, 0xec, 0xdd, 0x24, 0x55, 0xa5, 0xa0, 0x0a, 0x25, 0x12, 0x81, 0x54, 0xb4,
	0x2a, 0x8b, 0xc4, 0xa1, 0x08, 0x85, 0xb1, 0xfd, 0xc4, 0x19, 0x6a, 0xcf, 0x38, 0x33, 0xe3, 0x40,
	0x54, 0x45, 0x42, 0xa8, 0x47, 0x0e, 0x55, 0x78, 0x15, 0x1c, 0x2b, 0x24, 0xce, 0x1c, 0x7b, 0xac,
	0x84, 0x84, 0x38, 0xa1, 0x28, 0xe9, 0x95, 0xf7, 0x80, 0x3c, 0x1e, 0x6f, 0x76, 0xd3, 0x6c, 0x36,
	0xbd, 0x21, 0x71, 0x5a, 0x8f, 0xfd, 0x3c, 0xdf, 0xe7, 0x33, 0xcf, 0x7c, 0xfd, 0x78, 0xd1, 0xdb,
	0x6a, 0xab, 0xa0, 0x71, 0x90, 0x51, 0xf9, 0x00, 0x74, 0x46, 0x1f, 0x80, 0x0c, 0xb6, 0xbb, 0x21,
	0x68, 0xda, 0x0d, 0xb6, 0x0a, 0x90, 0x3b, 0x7e, 0x2e, 0x85, 0x16, 0x78, 0xc6, 0x84, 0xf9, 0x03,
	0x61, 0xbe, 0x0d, 0x73, 0xdf, 0x1f, 0xad, 0x30, 0x18, 0x6e, 0x74, 0xdc, 0x99, 0x48, 0xa8, 0x4c,
	0xa8, 0x75, 0xb3, 0x0a, 0xaa, 0x85, 0x7d, 0xf4, 0x5e, 0xb5, 0x0a, 0x42, 0xaa, 0xa0, 0xaa, 0xdd,
	0xd7, 0xc9, 0x69, 0xc2, 0x38, 0xd5, 0x4c, 0x70, 0x1b, 0xdb, 0x1e, 0x8c, 0xad, 0xa3, 0x22, 0xc1,
	0xea, 0xe7, 0x97, 0x12, 0x91, 0x88, 0xaa, 0x46, 0x79, 0x55, 0x17, 0x4f, 0x84, 0x48, 0x52, 0x08,
	0xcc, 0x2a, 0x2c, 0x36, 0x02, 0xca, 0xed, 0xfe, 0xdc, 0x2b, 0xc7, 0x1f, 0x69, 0x96, 0x81, 0xd2,
	0x34, 0xcb, 0x6d, 0xc0, 0x1b, 0x36, 0x80, 0xe6, 0x2c, 0xa0, 0x9c, 0x0b, 0x6d, 0x70, 0x6a, 0xf6,
	0xea, 0x27, 0x9a, 0x4b, 0x80, 0xcf, 0x89, 0x1c, 0x38, 0xcd, 0xd9, 0xf6, 0x7c, 0x20, 0x72, 0x13,
	0xf3, 0x62, 0xbc, 0x77, 0x09, 0xe1, 0xcf, 0xca, 0x1d, 0xde, 0xa3, 0x92, 0x66, 0xaa, 0x07, 0x5b,
	0x05, 0x28, 0xed, 0x7d, 0x81, 0x5e, 0x1d, 0xba, 0xab, 0x72, 0xc1, 0x15, 0xe0, 0x0f, 0xd1, 0x54,
	0x6e, 0xee, 0xb4, 0x1c, 0xe2, 0x5c, 0xbb, 0x30, 0x7f, 0xd5, 0x1f, 0x79, 0x18, 0x7e, 0x95, 0xba,
	0xd2, 0x7c, 0xfa, 0xd7, 0x95, 0x89, 0x9e, 0x4d, 0xf3, 0x9e, 0x38, 0xa8, 0x65, 0x84, 0xef, 0x98,
	0x8c, 0x3b, 0x65, 0x46, 0x5d, 0x14, 0xb7, 0xd0, 0x79, 0x1a, 0xc7, 0x12, 0x54, 0x25, 0x3f, 0xdd,
	0xab, 0x97, 0xf8, 0x75, 0x74, 0x3e, 0xa7, 0x4c, 0xae, 0xb3, 0xb8, 0x35, 0x49, 0x9c, 0x6b, 0xcd,
	0x52, 0x8f, 0xc9, 0xb5, 0x18, 0xbb, 0xe8, 0x7f, 0x90, 0xb2, 0x84, 0x85, 0x29, 0xb4, 0x1a, 0x26,
	0xa7, 0xbf, 0xc6, 0xab, 0x08, 0x1d, 0x9d, 0x56, 0xab, 0x69, 0x80, 0xdf, 0xf1, 0xed, 0x41, 0x97,
	0xc7, 0xe5, 0x57, 0xb6, 0x3a, 0x02, 0x4e, 0xc0, 0xa2, 0xf4, 0x06, 0x32, 0xbd, 0x5f, 0x1d, 0x34,
	0x73, 0x02, 0xb3, 0x6d, 0xc9, 0x3d, 0x74, 0x71, 0x60, 0xf7, 0x25, 0x79, 0xc3, 0xd4, 0x19, 0xdd,
	0x98, 0x01, 0x19, 0xdb, 0x9d, 0x21, 0x05, 0xfc, 0xf1, 0x10, 0xf7, 0xa4, 0xe1, 0x9e, 0x1d, 0xcb,
	0x5d, 0xe1, 0x0c, 0x81, 0x77, 0xd1, 0x65, 0xc3, 0xbd, 0xc6, 0x23, 0xe0, 0x9a, 0x6d, 0xc3, 0xd8,
	0x46, 0x7b, 0x21, 0x7a, 0xed, 0x78, 0x8a, 0xdd, 0xe7, 0x27, 0x68, 0x9a, 0xd5, 0x37, 0xed, 0xe9,
	0xbf, 0x75, 0xca, 0x26, 0xfb, 0x02, 0x76, 0x8b, 0x47, 0xc9, 0xf3, 0x8f, 0xff, 0x8f, 0xce, 0x99,
	0x22, 0xf8, 0xb7, 0x49, 0x34, 0x55, 0xd9, 0x04, 0xcf, 0x9d, 0xa2, 0xf5, 0xa2, 0x3f, 0x5d, 0xff,
	0xac, 0xe1, 0x15, 0xbd, 0xf7, 0x87, 0xb3, 0xb7, 0xfc, 0xb3, 0xe3, 0x76, 0x7b, 0xa0, 0x0b, 0xc9,
	0x15, 0xa1, 0x69, 0x4a, 0x8c, 0x25, 0x41, 0x83, 0x54, 0x44, 0x6c, 0x10, 0xbd, 0x09, 0x64, 0x40,
	0x8d, 0x64, 0x22, 0x2e, 0x52, 0xf0, 0x3d, 0x8d, 0xda, 0xab, 0x8c, 0xc7, 0x44, 0x14, 0x9a, 0x64,
	0x42, 0x02, 0xa1, 0x61, 0x79, 0x59, 0x86, 0x57, 0x9e, 0xc6, 0xbd, 0x4d, 0xad, 0x73, 0xb5, 0x14,
	0x04, 0x09, 0xd3, 0x9b, 0x45, 0xe8, 0x47, 0x22, 0xb3, 0xe3, 0xa4, 0x44, 0x9c, 0x4b, 0x69, 0xa8,
	0x82, 0x6a, 0x30, 0x85, 0xa9, 0x08, 0x83, 0x8c, 0x32, 0x1e, 0x7c, 0x37, 0x34, 0xa4, 0x54, 0x0e,
	0x51, 0xd0, 0xb9, 0xb9, 0x5e, 0x09, 0xfa, 0x59, 0xfc, 0xc3, 0xef, 0xcf, 0x7f, 0x9a, 0x7c, 0x13,
	0x5f, 0x0d, 0x46, 0x0f, 0x34, 0x5b, 0x7c, 0xbf, 0x89, 0x2e, 0x0e, 0xfa, 0x12, 0x2f, 0x8c, 0xeb,
	0xcc, 0x09, 0x6f, 0x9e, 0xbb, 0xf8, 0x72, 0x49, 0xb6, 0xa9, 0xcf, 0x1b, 0x7b, 0xcb, 0x4f, 0x1a,
	0xee, 0x07, 0xfd, 0xa6, 0x92, 0x94, 0x29, 0x5d, 0x36, 0xb3, 0x6c, 0x6f, 0xa5, 0x45, 0x2a, 0x53,
	0x93, 0x6f, 0x99, 0xde, 0x24, 0x47, 0xde, 0x24, 0x12, 0x54, 0x91, 0x6a, 0xdf, 0xdb, 0x44, 0x73,
	0xa3, 0xda, 0x6b, 0x5c, 0x4e, 0x28, 0x8f, 0x09, 0x48, 0x29, 0x24, 0x89, 0x44, 0x0c, 0x0a, 0xdf,
	0x3c, 0x73, 0xb7, 0xb5, 0x04, 0xa8, 0xba, 0x1d, 0x8b, 0x48, 0xdd, 0x7e, 0xe4, 0xa0, 0xc6, 0x62,
	0xa7, 0x83, 0x77, 0xd1, 0x85, 0x15, 0x1a, 0x93, 0x7a, 0xd2, 0x71, 0xf4, 0x0a, 0xcd, 0xf3, 0x94,
	0x45, 0x86, 0x2b, 0xf8, 0x46, 0x09, 0x8e, 0xef, 0x3f, 0xf4, 0xca, 0x62, 0xde, 0xd2, 0xc2, 0x75,
	0x2f, 0x03, 0xa5, 0x68, 0x02, 0xde, 0x92, 0x27, 0xf3, 0xa8, 0x22, 0x59, 0x32, 0x28, 0xe4, 0x16,
	0x59, 0xe3, 0xdb, 0x34, 0x65, 0xf1, 0xb2, 0x4c, 0x8a, 0x0c, 0xb8, 0x26, 0x31, 0xa8, 0x88, 0xdc,
	0x22, 0x90, 0xe5, 0x7a, 0x87, 0x48, 0x5b, 0xe0, 0xba, 0x17, 0x83, 0xa6, 0x2c, 0x55, 0xde, 0xd2,
	0x97, 0x5f, 0xed, 0xde, 0xfe, 0xde, 0x41, 0x8d, 0x1b, 0x9d, 0x0e, 0xde, 0x41, 0x97, 0xd7, 0xb8,
	0x06, 0xc9, 0x69, 0x4a, 0x3e, 0x07, 0xb9, 0x0d, 0x92, 0x7c, 0x54, 0x8a, 0x7b, 0x5f, 0x9f, 0x00,
	0xf4, 0x69, 0x0d, 0xd4, 0x1d, 0x4b, 0x64, 0x25, 0x6b, 0x14, 0x23, 0x39, 0x8c, 0x60, 0xcc, 0xf5,
	0x2e, 0x9e, 0x0d, 0xce, 0xf4, 0xb5, 0x54, 0x78, 0xff, 0x1c, 0x9a, 0xee, 0xbf, 0xce, 0xb8, 0x33,
	0xce, 0x2a, 0xc7, 0xa7, 0x8d, 0xdb, 0x7d, 0x89, 0x0c, 0xeb, 0xac, 0xbf, 0x9b, 0x7b, 0xcb, 0xbf,
	0x34, 0x5d, 0xbf, 0x76, 0xd6, 0xb1, 0x97, 0x73, 0x56, 0x91, 0x28, 0xa5, 0x2c, 0xa3, 0x61, 0x0a,
	0xa4, 0x3f, 0x58, 0xfe, 0x83, 0x66, 0xfa, 0xd1, 0x60, 0x2c, 0xe2, 0x47, 0xce, 0x30, 0x47, 0x71,
	0x02, 0x07, 0xad, 0x39, 0x6e, 0x9c, 0xce, 0x71, 0x57, 0xe8, 0x55, 0x51, 0xf0, 0xb8, 0x06, 0xe8,
	0xf7, 0x97, 0xd8, 0x8f, 0x04, 0xe1, 0x42, 0x93, 0x8d, 0x32, 0xe4, 0x5f, 0xea, 0xed, 0x0e, 0xf6,
	0x4f, 0xf1, 0x76, 0x7f, 0x3f, 0xc1, 0x43, 0xbb, 0xa1, 0xdd, 0x95, 0xbb, 0x4f, 0x0f, 0xda, 0xce,
	0xb3, 0x83, 0xb6, 0xb3, 0x7f, 0xd0, 0x76, 0x1e, 0x1f, 0xb6, 0x27, 0x9e, 0x1d, 0xb6, 0x27, 0xfe,
	0x3c, 0x6c, 0x4f, 0xdc, 0x5f, 0x1c, 0xeb, 0x8c, 0xe1, 0x51, 0xae, 0x77, 0x72, 0x50, 0xe1, 0x94,
	0xf9, 0x6f, 0xb5, 0xf0, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x90, 0x39, 0x7f, 0xd3, 0x0a,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns parameters of the marketmaker module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// MarketMakers returns all market makers.
	MarketMakers(ctx context.Context, in *QueryMarketMakersRequest, opts ...grpc.CallOption) (*QueryMarketMakersResponse, error)
	// Incentive returns a specific incentive.
	Incentive(ctx context.Context, in *QueryIncentiveRequest, opts ...grpc.CallOption) (*QueryIncentiveResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/squad.marketmaker.v1beta1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MarketMakers(ctx context.Context, in *QueryMarketMakersRequest, opts ...grpc.CallOption) (*QueryMarketMakersResponse, error) {
	out := new(QueryMarketMakersResponse)
	err := c.cc.Invoke(ctx, "/squad.marketmaker.v1beta1.Query/MarketMakers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Incentive(ctx context.Context, in *QueryIncentiveRequest, opts ...grpc.CallOption) (*QueryIncentiveResponse, error) {
	out := new(QueryIncentiveResponse)
	err := c.cc.Invoke(ctx, "/squad.marketmaker.v1beta1.Query/Incentive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns parameters of the marketmaker module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// MarketMakers returns all market makers.
	MarketMakers(context.Context, *QueryMarketMakersRequest) (*QueryMarketMakersResponse, error)
	// Incentive returns a specific incentive.
	Incentive(context.Context, *QueryIncentiveRequest) (*QueryIncentiveResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) MarketMakers(ctx context.Context, req *QueryMarketMakersRequest) (*QueryMarketMakersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarketMakers not implemented")
}
func (*UnimplementedQueryServer) Incentive(ctx context.Context, req *QueryIncentiveRequest) (*QueryIncentiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Incentive not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/squad.marketmaker.v1beta1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MarketMakers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMarketMakersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MarketMakers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/squad.marketmaker.v1beta1.Query/MarketMakers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MarketMakers(ctx, req.(*QueryMarketMakersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Incentive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIncentiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Incentive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/squad.marketmaker.v1beta1.Query/Incentive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Incentive(ctx, req.(*QueryIncentiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "squad.marketmaker.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "MarketMakers",
			Handler:    _Query_MarketMakers_Handler,
		},
		{
			MethodName: "Incentive",
			Handler:    _Query_Incentive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "squad/marketmaker/v1beta1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryMarketMakersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMarketMakersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMarketMakersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.Eligible) > 0 {
		i -= len(m.Eligible)
		copy(dAtA[i:], m.Eligible)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Eligible)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PairId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PairId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMarketMakersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMarketMakersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMarketMakersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Marketmakers) > 0 {
		for iNdEx := len(m.Marketmakers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Marketmakers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryIncentiveRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIncentiveRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIncentiveRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryIncentiveResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIncentiveResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIncentiveResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Incentive.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryMarketMakersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.PairId != 0 {
		n += 1 + sovQuery(uint64(m.PairId))
	}
	l = len(m.Eligible)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMarketMakersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Marketmakers) > 0 {
		for _, e := range m.Marketmakers {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryIncentiveRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryIncentiveResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Incentive.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMarketMakersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMarketMakersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMarketMakersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PairId", wireType)
			}
			m.PairId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PairId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Eligible", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Eligible = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMarketMakersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMarketMakersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMarketMakersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Marketmakers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Marketmakers = append(m.Marketmakers, MarketMaker{})
			if err := m.Marketmakers[len(m.Marketmakers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIncentiveRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIncentiveRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIncentiveRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIncentiveResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIncentiveResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIncentiveResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Incentive", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Incentive.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
