name: "Pull Request Labeler"
# Labeler workflow action automatically label new pull requests based on the paths of files being changed
# See the .github/labeler.yml for the configuration
on:
  - pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"